const CANVAS_EXPORT_CONTRACT = [
  ['sessions', ['sessionId', 'studentCode', 'condition', 'phase', 'attemptNumber', 'theme', 'taskPrompt', 'status', 'textEditable', 'ideationTextInitial', 'ideationTextFinal', 'ideationTextVersion', 'activeSeconds', 'completionReason', 'timingStartedAt', 'timingStartedAtBeijing', 'submittedAt', 'submittedAtBeijing', 'lastOperationSeq', 'assistantState', 'createdAt', 'createdAtBeijing', 'updatedAt', 'updatedAtBeijing', 'configSnapshot', 'timeZone']],
  ['canvas_operations', ['operationId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'seq', 'operationType', 'activeSeconds', 'payload', 'occurredAtClient', 'occurredAtClientBeijing', 'occurredAt', 'occurredAtBeijing', 'timeZone']],
  ['snapshot_index', ['snapshotId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'snapshotKind', 'sampleIndex', 'activeSeconds', 'operationSeq', 'mimeType', 'filePath', 'fileSize', 'sha256', 'width', 'height', 'sceneState', 'assistantState', 'capturedAt', 'capturedAtBeijing', 'timeZone']],
  ['ideation_revisions', ['revisionId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'version', 'previousText', 'currentText', 'activeSeconds', 'occurredAtClient', 'occurredAtClientBeijing', 'occurredAt', 'occurredAtBeijing', 'timeZone']],
  ['assistant_messages', ['messageId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'role', 'source', 'aiCycleId', 'requestId', 'content', 'ideationTextVersion', 'snapshotId', 'responseStatus', 'responseError', 'modelSlot', 'modelLabel', 'modelName', 'latencyMs', 'activeSeconds', 'createdAt', 'createdAtBeijing', 'timeZone']],
  ['assistant_events', ['eventId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'eventType', 'activeSeconds', 'payload', 'occurredAtClient', 'occurredAtClientBeijing', 'occurredAt', 'occurredAtBeijing', 'timeZone']],
  ['assistant_mask_hovers', ['hoverId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'pairingStatus', 'startEventId', 'endEventId', 'startSequenceNumber', 'endSequenceNumber', 'startAiState', 'endAiState', 'startPanelState', 'endPanelState', 'assistantWasObscured', 'pointerType', 'startPanelX', 'startPanelY', 'endPanelX', 'endPanelY', 'startActiveSeconds', 'endActiveSeconds', 'activeDurationSeconds', 'startElapsedMs', 'endElapsedMs', 'hoverDurationMs', 'endReason', 'startedAtClient', 'startedAtClientBeijing', 'endedAtClient', 'endedAtClientBeijing', 'startedAt', 'startedAtBeijing', 'endedAt', 'endedAtBeijing', 'startPayload', 'endPayload', 'timeZone']],
  ['flow_evaluations', ['evaluationId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'activeSeconds', 'windowSeconds', 'metrics', 'thresholds', 'passed', 'consecutivePasses', 'decision', 'evaluatedAt', 'evaluatedAtBeijing', 'timeZone']],
  ['ai_cycles', ['cycleId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'conversationId', 'cycleNumber', 'triggerKind', 'status', 'parentWithdrawalId', 'openedActiveSeconds', 'firstPromptActiveSeconds', 'responseCompletedActiveSeconds', 'returnedToCanvasActiveSeconds', 'closedActiveSeconds', 'createdAt', 'createdAtBeijing', 'closedAt', 'closedAtBeijing', 'timeZone']],
  ['withdrawal_events', ['withdrawalEventId', 'sessionId', 'aiCycleId', 'studentCode', 'phase', 'attemptNumber', 'withdrawalNumber', 'status', 'candidateStartedActiveSeconds', 'candidateUpdatedActiveSeconds', 'fadeStartedActiveSeconds', 'completedActiveSeconds', 'cancelledActiveSeconds', 'cancellationReason', 'triggerMetrics', 'triggerRules', 'createdAt', 'createdAtBeijing', 'completedAt', 'completedAtBeijing', 'cancelledAt', 'cancelledAtBeijing', 'timeZone']],
  ['agency_decisions', ['decisionId', 'sessionId', 'aiCycleId', 'withdrawalEventId', 'studentCode', 'phase', 'attemptNumber', 'decisionIndex', 'requestId', 'activeSeconds', 'assistantState', 'evidenceInput', 'promptSystem', 'promptInput', 'rawResponse', 'normalizedDecision', 'action', 'confidence', 'supportNeed', 'supportEpisodeStatus', 'withdrawalType', 'evidenceForWithdrawal', 'evidenceAgainstWithdrawal', 'uncertainties', 'nextReviewSeconds', 'validationStatus', 'validationError', 'executionStatus', 'executionReason', 'snapshotId', 'modelSlot', 'modelLabel', 'modelName', 'fallback', 'responseError', 'latencyMs', 'requestedAt', 'requestedAtBeijing', 'decidedAt', 'decidedAtBeijing', 'timeZone']],
  ['canvas_event_log', ['eventId', 'sessionId', 'studentCode', 'phase', 'attemptNumber', 'sequenceNumber', 'eventType', 'currentAiState', 'aiCycleId', 'withdrawalEventId', 'activeSeconds', 'elapsedMs', 'occurredAtClient', 'occurredAtClientBeijing', 'occurredAt', 'occurredAtBeijing', 'systemVersion', 'ruleVersion', 'payload', 'timeZone']],
  ['data_integrity', ['sessionId', 'studentCode', 'phase', 'attemptNumber', 'eventCount', 'snapshotCount', 'withdrawalCount', 'valid', 'issues']],
  ['submission_reviews', ['reviewId', 'sessionId', 'snapshotId', 'studentCode', 'phase', 'attemptNumber', 'submissionNumber', 'status', 'score', 'passScore', 'forcedAcceptance', 'feedback', 'criteria', 'modelSlot', 'modelLabel', 'modelName', 'fallback', 'responseError', 'latencyMs', 'requestedAt', 'requestedAtBeijing', 'reviewedAt', 'reviewedAtBeijing', 'timeZone']],
  ['practice_activity_events', ['eventId', 'studentCode', 'actorRole', 'module', 'actionType', 'canvasSessionId', 'ideationAttemptId', 'payload', 'occurredAt', 'occurredAtBeijing', 'timeZone']],
  ['config_snapshot', ['sessionId', 'studentCode', 'phase', 'configSnapshot']],
  ['data_dictionary', ['sheet', 'meaning']]
];

module.exports = { CANVAS_EXPORT_CONTRACT };
