import { useEffect, useState } from 'react';
import { ArrowLeft, FlaskConical, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { api, patch, post } from './api';
import { useBrand } from './BrandContext';

function NodeEditor({ node, token, onChanged, onMessage }) {
  const [form, setForm] = useState({ ...node, apiKey: '' }); const [busy, setBusy] = useState('');
  useEffect(() => { setForm({ ...node, apiKey: '' }); }, [node]);
  const save = async () => { if (!form.label.trim() || !form.baseUrl.trim() || !form.model.trim() || (!node.hasApiKey && !form.apiKey.trim())) return onMessage('Label, base URL, model, and API key are required.', true); setBusy('save'); try { await patch(`/teacher/model-nodes/${node.id}`, form, token); onMessage('Model node saved.'); await onChanged(); } catch (error) { onMessage(error.message, true); } finally { setBusy(''); } };
  const test = async () => { setBusy('test'); try { const result = await post(`/teacher/model-nodes/${node.id}/test`, {}, token); onMessage(result.message); } catch (error) { onMessage(error.message, true); } finally { setBusy(''); } };
  const remove = async () => { if (!window.confirm(`Delete ${node.label}?`)) return; setBusy('delete'); try { await api(`/teacher/model-nodes/${node.id}`, { method: 'DELETE' }, token); onMessage('Model node deleted.'); await onChanged(); } catch (error) { onMessage(error.message, true); } finally { setBusy(''); } };
  return <article className="model-node editor"><div className="model-node-fields"><label>Label<input value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} /></label><label>Priority<input type="number" min="0" max="10000" value={form.priority} onChange={(e) => setForm({ ...form, priority: Number(e.target.value) })} /></label><label className="wide">Base URL<input value={form.baseUrl} onChange={(e) => setForm({ ...form, baseUrl: e.target.value })} /></label><label>Model<input value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /></label><label>New API key <small>{node.hasApiKey ? 'Leave blank to keep the saved key' : 'Required'}</small><input type="password" value={form.apiKey} onChange={(e) => setForm({ ...form, apiKey: e.target.value })} autoComplete="new-password" required={!node.hasApiKey} /></label></div><div className="model-node-actions"><label className="toggle-row"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} /><span>Enabled</span></label><button className="button secondary" onClick={test} disabled={Boolean(busy)}><FlaskConical size={17} />{busy === 'test' ? 'Testing...' : 'Test'}</button><button className="button secondary" onClick={save} disabled={Boolean(busy)}><Save size={17} />{busy === 'save' ? 'Saving...' : 'Save'}</button><button className="icon-danger" title="Delete model node" onClick={remove} disabled={Boolean(busy)}><Trash2 size={19} /></button></div></article>;
}

export default function ModelSettings({ token, onBack }) {
  const { displayName } = useBrand(); const [nodes, setNodes] = useState([]); const [form, setForm] = useState({ label: '', baseUrl: 'https://api.openai.com/v1', model: 'gpt-5.5', apiKey: '', priority: 100, enabled: true }); const [message, setMessage] = useState({ text: '', error: false }); const [busy, setBusy] = useState(false);
  const notify = (text, error = false) => setMessage({ text, error }); const load = async () => { try { setNodes((await api('/teacher/model-nodes', {}, token)).nodes); } catch (error) { notify(error.message, true); } }; useEffect(() => { load(); }, []);
  const create = async (event) => { event.preventDefault(); setBusy(true); notify(''); try { await post('/teacher/model-nodes', form, token); setForm({ ...form, label: '', apiKey: '' }); await load(); notify('Model node added.'); } catch (error) { notify(error.message, true); } finally { setBusy(false); } };
  return <section><button className="button ghost" onClick={onBack}><ArrowLeft size={18} />{displayName} Teacher Console</button><div className="app-header"><div><span className="eyebrow">{displayName} MODEL SETTINGS</span><h1>{displayName} AI Service Nodes</h1></div><button className="button ghost" onClick={load}><RefreshCw size={18} />Refresh</button></div><p className="muted">Nodes are tried by priority. Keys are encrypted before database storage, and each saved node can be tested before class.</p>{message.text && <div className={message.error ? 'error' : 'success'}>{message.text}</div>}<form className="panel model-form" onSubmit={create}><h2>Add a model node</h2><div className="form-row"><label>Label<input value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} required /></label><label>Priority<input type="number" min="0" max="10000" value={form.priority} onChange={(e) => setForm({ ...form, priority: Number(e.target.value) })} /></label><label>Base URL<input value={form.baseUrl} onChange={(e) => setForm({ ...form, baseUrl: e.target.value })} required /></label><label>Model<input value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} required /></label></div><label>API key<input type="password" value={form.apiKey} onChange={(e) => setForm({ ...form, apiKey: e.target.value })} autoComplete="new-password" required /></label><button className="button primary" disabled={busy}><Plus size={18} />{busy ? 'Adding...' : 'Add node'}</button></form><div className="model-node-list">{nodes.map((node) => <NodeEditor key={node.id} node={node} token={token} onChanged={load} onMessage={notify} />)}{!nodes.length && <div className="empty"><FlaskConical size={30} /><h3>No saved model nodes</h3><p>Add a node above or use the environment-level fallback model.</p></div>}</div></section>;
}
